import pandas as pd
import matplotlib.pyplot as plt

# Load dataset (generated by forecast.py)
df = pd.read_csv("forecast.csv")

# Bar chart - daily temperatures
plt.bar(df["Date"], df["Temperature"], color="skyblue")
plt.xlabel("Date")
plt.ylabel("Temperature (°C)")
plt.title("Daily Temperatures")
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig("temperatures.png")
plt.show()
