import pandas as pd
import matplotlib.pyplot as plt

# Load dataset (generated by forecast.py)
df = pd.read_csv("forecast.csv")

# Line chart - temperature trend
plt.plot(df["Date"], df["Temperature"], marker="o", color="orange")
plt.xlabel("Date")
plt.ylabel("Temperature (°C)")
plt.title("Temperature Trend Over Time")
plt.xticks(rotation=45)
plt.grid(True)
plt.tight_layout()
plt.savefig("trend.png")
plt.show()
